name: portfolio_app
description: A new Flutter project.

publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  timelines: ^0.1.0
  font_awesome_flutter: ^10.5.0
  velocity_x: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: custom
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          style: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          style: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          style: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: 900

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
